version: '3'

services:
  backend:
    restart: always
    build: .
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 801:8888
  frontend:
    restart: always
    image: nginx
    ports:
      - 83:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx 
      - ./website:/usr/share/nginx/html
    depends_on:
      - backend
